# Regenerate: kubeseal --namespace auction-system-staging < secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auction-system-secrets
  namespace: auction-system-staging
spec:
  encryptedData:
    DB_URL: AgSTAGING...PLACEHOLDER...==
    JWT_SECRET: AgSTAGING...PLACEHOLDER...==
    REDIS_PASSWORD: AgSTAGING...PLACEHOLDER...==
    POSTGRES_PASSWORD: AgSTAGING...PLACEHOLDER...==
  template:
    metadata:
      name: auction-system-secrets
      namespace: auction-system-staging
    type: Opaque
