# Regenerate: kubeseal --namespace auction-system-dev < secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auction-system-secrets
  namespace: auction-system-dev
spec:
  encryptedData:
    DB_URL: AgDEV...PLACEHOLDER...==
    JWT_SECRET: AgDEV...PLACEHOLDER...==
    REDIS_PASSWORD: AgDEV...PLACEHOLDER...==
    POSTGRES_PASSWORD: AgDEV...PLACEHOLDER...==
  template:
    metadata:
      name: auction-system-secrets
      namespace: auction-system-dev
    type: Opaque
