apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-system-config
data:
  APP_ENV: development
  USER_SERVICE_URL: http://user-service.auction-system-dev.svc.cluster.local
  AUCTION_SERVICE_URL: http://auction-service.auction-system-dev.svc.cluster.local
  BID_SERVICE_URL: http://bid-service.auction-system-dev.svc.cluster.local
  NOTIFICATION_SERVICE_URL: http://notification-service.auction-system-dev.svc.cluster.local
  REDIS_ADDR: redis-master.auction-system-dev.svc.cluster.local:6379
  KAFKA_BROKERS: kafka-0.kafka-headless.auction-system-dev.svc.cluster.local:9092
  OTEL_EXPORTER_OTLP_ENDPOINT: ""
  RATE_LIMIT_PER_MINUTE: "60"
  PROXY_TIMEOUT_SEC: "30"
  PROXY_RETRIES: "2"
