name: Notification Service CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - "services/notification-service/**"
      - ".github/workflows/notification-service.yml"
  pull_request:
    branches: [main]
    paths:
      - "services/notification-service/**"

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-go-service.yml
    with:
      service-name:       notification-service
      service-path:       services/notification-service
      dockerfile:         deployments/docker/notification.Dockerfile
      go-version:         "1.22"
      coverage-threshold: "60"
    secrets:
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
